-- =====================================================================
-- ⚠️  FILE INI SUDAH TIDAK DIPAKAI LAGI — JANGAN DIJALANKAN
-- =====================================================================
--
-- Struktur tabel sekarang HANYA didefinisikan di:
--     backend/app/models/threat.py
--
-- KENAPA DIPENSIUNKAN:
-- Isi file ini sempat berbeda dengan definisi ORM, dan bedanya tidak
-- kelihatan saat aplikasi jalan:
--
--   1. domain_reputation.id  -> di sini SERIAL (angka urut),
--                               di ORM UUID                    [BENTROK]
--   2. file_signatures       -> di sini sha256_hash jadi primary key,
--                               di ORM ada kolom id UUID       [BENTROK]
--   3. domain_features_cache, scan_feedback, model_versions
--                            -> ada di sini, dulu belum ada di ORM
--
-- Bentrokan nomor 1 dan 2 adalah bom waktu: perintah
-- Base.metadata.create_all() hanya MEMBUAT tabel yang belum ada, dan
-- tidak pernah mengubah tabel yang sudah terlanjur ada. Jadi selama
-- tabelnya sudah dibuat lewat file ini, aplikasi tampak baik-baik saja
-- sampai tabel tersebut benar-benar mulai dipakai — baru di situ ORM
-- mengirim UUID ke kolom angka, lalu gagal.
--
-- Semua perintah di bawah sengaja DINONAKTIFKAN (diberi tanda komentar)
-- supaya tidak bisa terjalankan tanpa sengaja dan menghidupkan lagi
-- struktur tabel yang salah. Isinya dibiarkan utuh sebagai catatan.
--
-- CARA MEMBUAT TABEL SEKARANG:
--   Cukup jalankan backend. main.py otomatis membuat semua tabel.
--
-- CARA MENGUBAH STRUKTUR TABEL NANTI:
--   Jangan tulis SQL manual. Pakai Alembic (sudah ada di requirements):
--       alembic revision --autogenerate -m "keterangan"
--       alembic upgrade head
-- =====================================================================

-- Tabel reputasi domain
-- CREATE TABLE domain_reputation (
--     id              SERIAL PRIMARY KEY,
--     domain          VARCHAR(255) UNIQUE NOT NULL,
--     risk_score      FLOAT DEFAULT 0.0,
--     threat_type     VARCHAR(50),
--     first_seen      TIMESTAMP DEFAULT NOW(),
--     last_scanned    TIMESTAMP DEFAULT NOW(),
--     scan_count      INTEGER DEFAULT 1,
--     confirmed_bad   BOOLEAN DEFAULT FALSE,
--     source          VARCHAR(50) DEFAULT 'ml_detected'
-- );

-- Cache fitur network domain
-- CREATE TABLE domain_features_cache (
--     domain          VARCHAR(255) PRIMARY KEY,
--     features_json   JSONB,
--     cached_at       TIMESTAMP DEFAULT NOW(),
--     expires_at      TIMESTAMP
-- );

-- Database hash file berbahaya
-- CREATE TABLE file_signatures (
--     sha256_hash     CHAR(64) PRIMARY KEY,
--     file_type       VARCHAR(20),
--     threat_name     VARCHAR(100),
--     detected_at     TIMESTAMP DEFAULT NOW(),
--     source          VARCHAR(50)
-- );

-- History scan
-- CREATE TABLE scan_history (
--     id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     scan_type       VARCHAR(20) NOT NULL,
--     input_value     TEXT NOT NULL,
--     risk_score      FLOAT,
--     threat_label    VARCHAR(50),
--     features_json   JSONB,
--     shap_values     JSONB,
--     created_at      TIMESTAMP DEFAULT NOW()
-- );

-- Feedback untuk continuous learning
-- CREATE TABLE scan_feedback (
--     id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     scan_id         UUID REFERENCES scan_history(id),
--     ml_prediction   FLOAT,
--     user_correction VARCHAR(20),
--     created_at      TIMESTAMP DEFAULT NOW()
-- );

-- Versi model
-- CREATE TABLE model_versions (
--     id              SERIAL PRIMARY KEY,
--     model_type      VARCHAR(50),
--     version         VARCHAR(20),
--     accuracy        FLOAT,
--     f1_score        FLOAT,
--     trained_at      TIMESTAMP DEFAULT NOW(),
--     is_active       BOOLEAN DEFAULT FALSE
-- );
