"""tambah indeks scan_history dan ubah input_value jadi Text

Revision ID: 2967910c9fa5
Revises: d618c567f08a
Create Date: 2026-08-06 21:26:47.771726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2967910c9fa5'
down_revision: Union[str, None] = 'd618c567f08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_history', 'input_value',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_scan_history_created_at'), 'scan_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_history_scan_type'), 'scan_history', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scan_history_threat_label'), 'scan_history', ['threat_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_history_threat_label'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_scan_type'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_created_at'), table_name='scan_history')
    op.alter_column('scan_history', 'input_value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
