"""skema dasar ThreatSense

Revision ID: d618c567f08a
Revises: 
Create Date: 2026-08-06 21:24:58.205434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd618c567f08a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_features_cache',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_index(op.f('ix_domain_features_cache_expires_at'), 'domain_features_cache', ['expires_at'], unique=False)
    op.create_table('domain_reputation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_scanned', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('scan_count', sa.Integer(), nullable=True),
    sa.Column('confirmed_bad', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_reputation_domain'), 'domain_reputation', ['domain'], unique=True)
    op.create_table('file_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('threat_name', sa.String(length=255), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_signatures_sha256_hash'), 'file_signatures', ['sha256_hash'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('hash_sandi', sa.String(length=255), nullable=False),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scan_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('input_value', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('threat_label', sa.String(length=50), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shap_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deep_scan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_history_created_at'), 'scan_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_history_scan_type'), 'scan_history', ['scan_type'], unique=False)
    op.create_index(op.f('ix_scan_history_threat_label'), 'scan_history', ['threat_label'], unique=False)
    op.create_index(op.f('ix_scan_history_user_id'), 'scan_history', ['user_id'], unique=False)
    op.create_table('scan_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('ml_prediction', sa.Float(), nullable=True),
    sa.Column('user_correction', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_feedback_scan_id'), 'scan_feedback', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_feedback_scan_id'), table_name='scan_feedback')
    op.drop_table('scan_feedback')
    op.drop_index(op.f('ix_scan_history_user_id'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_threat_label'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_scan_type'), table_name='scan_history')
    op.drop_index(op.f('ix_scan_history_created_at'), table_name='scan_history')
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_file_signatures_sha256_hash'), table_name='file_signatures')
    op.drop_table('file_signatures')
    op.drop_index(op.f('ix_domain_reputation_domain'), table_name='domain_reputation')
    op.drop_table('domain_reputation')
    op.drop_index(op.f('ix_domain_features_cache_expires_at'), table_name='domain_features_cache')
    op.drop_table('domain_features_cache')
    # ### end Alembic commands ###
